/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duoc.cl.safe.forms;

import duoc.cl.safe.entity.SsfPersona;
import duoc.cl.safe.negocio.SsfPersonaBO;
import java.util.List;

/**
 *
 * @author Nacho
 */
public class Prueba extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lGetAll = new javax.swing.JLabel();
        lFind = new javax.swing.JLabel();
        lAdd = new javax.swing.JLabel();
        lRemove = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lGetAll.setText("jLabel1");

        lFind.setText("jLabel2");

        lAdd.setText("jLabel3");

        lRemove.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lRemove)
                    .addComponent(lAdd)
                    .addComponent(lFind)
                    .addComponent(lGetAll))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lGetAll)
                .addGap(18, 18, 18)
                .addComponent(lFind)
                .addGap(18, 18, 18)
                .addComponent(lAdd)
                .addGap(18, 18, 18)
                .addComponent(lRemove)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        SsfPersonaBO personaBO = new SsfPersonaBO();
        
        
        
        List<SsfPersona> listaP = personaBO.getAll();
        SsfPersona objP = null;
        for (SsfPersona p : listaP) {
            objP = p;
            break;
        }
        if (objP != null) {
            lGetAll.setText("Nombre: "+objP.getNombre()+", obtenido por método getAll()");
        } else {
            lGetAll.setText("nope");
        }
        
        SsfPersona objP2 = personaBO.find(22);
        if (objP2 != null) {
            lFind.setText("Nombre: "+objP2.getNombre()+", obtenido por método find()");
        } else {
            lFind.setText("nope");
        }
        
        SsfPersona objAdd = new SsfPersona();
        objAdd.setNombre("Nuevo");
        personaBO.add(objAdd);
        listaP = personaBO.getAll();
        int id = 0;
        for (SsfPersona p : listaP) {
            if (p.getNombre().equals("Nuevo")) {
                lAdd.setText("Nombre: "+p.getNombre()+", obtenido por método add()");
                id=p.getId().intValue();
                break;
            }
        }
        
        if (personaBO.remove(id)) {
            lRemove.setText("Nuevo borrado");
        }else{
            lRemove.setText("borrado error");
        }
        
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAdd;
    private javax.swing.JLabel lFind;
    private javax.swing.JLabel lGetAll;
    private javax.swing.JLabel lRemove;
    // End of variables declaration//GEN-END:variables
}
